version: '3'
services:
  grafana:
    image: grafana/grafana-oss:9.3.6
    container_name: clabtmon-grafana
    hostname: clabtmon-grafana
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/dashboards/traffic_monitor.json:/var/lib/grafana/dashboards/traffic_monitor.json
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_SECURITY_ADMIN_USER=${CLABTMON_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${CLABTMON_PASSWORD}
    env_file:
      - .env
    restart: always
    user: "$PID:$GID"
  influxdb:
    image: influxdb:1.8.10-alpine
    container_name: clabtmon-influxdb
    hostname: clabtmon-influxdb
    volumes:
      - ./influxdb/data:/var/lib/influxdb
      - ./influxdb/init-influxdb.sh:/docker-entrypoint-initdb.d/init-influxdb.sh
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=clabtmon
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_ADMIN_USER=${CLABTMON_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${CLABTMON_PASSWORD}
    env_file:
      - .env
    restart: always
    user: "$PID:$GID"
  telegraf:
    image: telegraf:1.30
    container_name: clabtmon-telegraf
    hostname: clabtmon-telegraf
    volumes:
      - ./telegraf/settings:/etc/telegraf
    restart: always
    env_file:
      - .env
    networks:
      default:
        ipv4_address: 172.20.20.252

networks:
  default:
    external:
      name: clab