apiVersion: 1

datasources:
- name: clabtmon-influxdb
  type: influxdb
  access: proxy
  url: http://clabtmon-influxdb:8086
  database: clabtmon
  user: "$CLABTMON_USERNAME"
  secureJsonData:
    password: "$CLABTMON_PASSWORD"
  isDefault: true
  editable: true
  basicAuth: false